# spring.application.name=railway-ticketing
spring:
  application:
    name: railway-ticketing

  datasource:
    url: jdbc:mysql://localhost:3306/railway_ticketing?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}

#logging:
#  level:
#    root: INFO
#    com.lhkeeper.ticketing.railway_ticketing: DEBUG
#    com.baomidou.mybatisplus: INFO
#    org.mybatis: DEBUG

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl