# spring.application.name=railway-ticketing
spring:
  application:
    name: railway-ticketing

  datasource:
    url: jdbc:mysql://localhost:3306/railway_ticketing?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always